#!/usr/bin/env python3
"""Generate the C++ translation table from `locales/*.json`.

The web client ships twelve locale files with `en.json` as the base and every
other locale carrying only the keys it actually translates. This script turns
that into one C++ translation unit so the native client has the exact same
string coverage with no runtime JSON parsing and no embedded asset.

    python3 native/tools/gen_i18n.py

Run it again after editing any locale file; the output is deterministic.
"""

from __future__ import annotations

import json
import os
import sys

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
LOCALES_DIR = os.path.join(REPO_ROOT, "locales")
OUTPUT = os.path.join(REPO_ROOT, "native", "src", "i18n", "TranslationData.cpp")
HEADER = os.path.join(REPO_ROOT, "native", "include", "onow", "i18n", "TranslationData.h")

LOCALE_ORDER = ["en", "de", "es", "fr", "ja", "ko", "nl", "pl", "ro", "ru", "tr", "zh"]

LOCALE_NAMES = {
    "en": "English",
    "de": "Deutsch",
    "es": "Español",
    "fr": "Français",
    "ja": "日本語",
    "ko": "한국어",
    "nl": "Nederlands",
    "pl": "Polski",
    "ro": "Română",
    "ru": "Русский",
    "tr": "Türkçe",
    "zh": "中文",
}


def flatten(node, prefix=""):
    out = []
    if isinstance(node, dict):
        for key, value in node.items():
            path = f"{prefix}.{key}" if prefix else key
            out.extend(flatten(value, path))
    else:
        out.append((prefix, node))
    return out


def c_escape(text: str) -> str:
    return (
        text.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )


def load(locale: str):
    path = os.path.join(LOCALES_DIR, f"{locale}.json")
    if not os.path.exists(path):
        return {}
    with open(path, "r", encoding="utf-8") as handle:
        return dict(flatten(json.load(handle)))


def emit_table(name: str, entries) -> str:
    lines = [f"static const TranslationEntry {name}[] = {{"]
    for key, value in entries:
        lines.append(f'    {{"{c_escape(key)}", "{c_escape(value)}"}},')
    lines.append("};")
    return "\n".join(lines)


def main() -> int:
    base = load("en")
    if not base:
        print("en.json missing or empty", file=sys.stderr)
        return 1

    tables = [emit_table("kEnglish", sorted(base.items()))]
    locales = [("en", "kEnglish", len(base))]

    for code in LOCALE_ORDER:
        if code == "en":
            continue
        entries = load(code)
        overrides = sorted((k, v) for k, v in entries.items() if k in base and base[k] != v)
        table_name = f"k{code.capitalize()}"
        if overrides:
            tables.append(emit_table(table_name, overrides))
            locales.append((code, table_name, len(overrides)))
        else:
            tables.append(f"// {code} adds no overrides beyond en.\nstatic const TranslationEntry {table_name}[1] = {{\n    {{\"\", \"\"}},\n}};")
            locales.append((code, table_name, 0))

    header = [
        "// Generated by native/tools/gen_i18n.py — do not edit by hand.",
        "//",
        "// Declarations for the generated translation tables. `onow/i18n.h`",
        "// forward-declares `LocaleTable`; this header defines it so the",
        "// translator can read the tables without the definitions.",
        "#pragma once",
        "",
        "namespace onow {",
        "namespace i18n_data {",
        "",
        "struct TranslationEntry {",
        "    const char* key;",
        "    const char* value;",
        "};",
        "",
        "struct LocaleTable {",
        "    const char* code;",
        "    const char* display_name;",
        "    const TranslationEntry* entries;",
        "    int entry_count;",
        "};",
        "",
        "extern const LocaleTable kLocales[];",
        "extern const int kLocaleCount;",
        "",
        "} // namespace i18n_data",
        "} // namespace onow",
        "",
    ]

    out = [
        "// Generated by native/tools/gen_i18n.py — do not edit by hand.",
        "//",
        "// Every string the web client can show, in the twelve locales it ships,",
        "// as one flat table. `en` is the base; the other locales carry only the",
        "// keys whose text differs, which is exactly how the locale JSON files are",
        "// organised upstream.",
        "#include \"onow/i18n/TranslationData.h\"",
        "",
        "namespace onow {",
        "namespace i18n_data {",
        "",
    ]
    out.extend(tables)
    out.append("")
    out.append("const LocaleTable kLocales[] = {")
    for code, table, count in locales:
        out.append(f'    {{"{code}", "{LOCALE_NAMES[code]}", {table}, {count}}},')
    out.append("};")
    out.append("")
    out.append(f"const int kLocaleCount = {len(locales)};")
    out.append("")
    out.append("} // namespace i18n_data")
    out.append("} // namespace onow")
    out.append("")

    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
    os.makedirs(os.path.dirname(HEADER), exist_ok=True)
    with open(OUTPUT, "w", encoding="utf-8") as handle:
        handle.write("\n".join(out))
    with open(HEADER, "w", encoding="utf-8") as handle:
        handle.write("\n".join(header))

    total = sum(count for _, _, count in locales)
    print(f"wrote {OUTPUT}: {len(locales)} locales, {total} table entries")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
