// Generated by native/tools/gen_i18n.py — do not edit by hand.
//
// Declarations for the generated translation tables. `onow/i18n.h`
// forward-declares `LocaleTable`; this header defines it so the
// translator can read the tables without the definitions.
#pragma once

namespace onow {
namespace i18n_data {

struct TranslationEntry {
    const char* key;
    const char* value;
};

struct LocaleTable {
    const char* code;
    const char* display_name;
    const TranslationEntry* entries;
    int entry_count;
};

extern const LocaleTable kLocales[];
extern const int kLocaleCount;

} // namespace i18n_data
} // namespace onow
