#include "onow/gfx/GLLoader.h"

#include "onow/Log.h"

#if defined(_WIN32)
#include <windows.h>
#else
#include <dlfcn.h>
#endif

// Storage for the entry points the header declares at global scope. These have
// to be at global scope: ImGui's OpenGL 3 backend calls `glViewport(...)`
// directly.
#define ONOW_GL_DEFINE(name) PFNGL##name##PROC gl##name = nullptr
ONOW_GL_DEFINE(VIEWPORT);
ONOW_GL_DEFINE(SCISSOR);
ONOW_GL_DEFINE(CLEARCOLOR);
ONOW_GL_DEFINE(CLEAR);
ONOW_GL_DEFINE(ENABLE);
ONOW_GL_DEFINE(DISABLE);
ONOW_GL_DEFINE(ISENABLED);
ONOW_GL_DEFINE(GETINTEGERV);
ONOW_GL_DEFINE(GETERROR);
ONOW_GL_DEFINE(PIXELSTOREI);
ONOW_GL_DEFINE(POLYGONMODE);
ONOW_GL_DEFINE(BLENDEQUATION);
ONOW_GL_DEFINE(BLENDEQUATIONSEPARATE);
ONOW_GL_DEFINE(BLENDFUNCSEPARATE);
ONOW_GL_DEFINE(CLIPCONTROL);
ONOW_GL_DEFINE(CREATESHADER);
ONOW_GL_DEFINE(SHADERSOURCE);
ONOW_GL_DEFINE(COMPILESHADER);
ONOW_GL_DEFINE(GETSHADERIV);
ONOW_GL_DEFINE(GETSHADERINFOLOG);
ONOW_GL_DEFINE(DELETESHADER);
ONOW_GL_DEFINE(CREATEPROGRAM);
ONOW_GL_DEFINE(ATTACHSHADER);
ONOW_GL_DEFINE(DETACHSHADER);
ONOW_GL_DEFINE(LINKPROGRAM);
ONOW_GL_DEFINE(USEPROGRAM);
ONOW_GL_DEFINE(GETPROGRAMIV);
ONOW_GL_DEFINE(GETPROGRAMINFOLOG);
ONOW_GL_DEFINE(DELETEPROGRAM);
ONOW_GL_DEFINE(ISPROGRAM);
ONOW_GL_DEFINE(GETUNIFORMLOCATION);
ONOW_GL_DEFINE(UNIFORM1I);
ONOW_GL_DEFINE(UNIFORM1F);
ONOW_GL_DEFINE(UNIFORM2F);
ONOW_GL_DEFINE(UNIFORM4F);
ONOW_GL_DEFINE(UNIFORMMATRIX4FV);
ONOW_GL_DEFINE(GETATTRIBLOCATION);
ONOW_GL_DEFINE(ENABLEVERTEXATTRIBARRAY);
ONOW_GL_DEFINE(DISABLEVERTEXATTRIBARRAY);
ONOW_GL_DEFINE(VERTEXATTRIBPOINTER);
ONOW_GL_DEFINE(GETVERTEXATTRIBIV);
ONOW_GL_DEFINE(GETVERTEXATTRIBPOINTERV);
ONOW_GL_DEFINE(GENBUFFERS);
ONOW_GL_DEFINE(BINDBUFFER);
ONOW_GL_DEFINE(BUFFERDATA);
ONOW_GL_DEFINE(BUFFERSUBDATA);
ONOW_GL_DEFINE(DELETEBUFFERS);
ONOW_GL_DEFINE(GENVERTEXARRAYS);
ONOW_GL_DEFINE(BINDVERTEXARRAY);
ONOW_GL_DEFINE(DELETEVERTEXARRAYS);
ONOW_GL_DEFINE(GENTEXTURES);
ONOW_GL_DEFINE(BINDTEXTURE);
ONOW_GL_DEFINE(TEXIMAGE2D);
ONOW_GL_DEFINE(TEXPARAMETERI);
ONOW_GL_DEFINE(DELETETEXTURES);
ONOW_GL_DEFINE(ACTIVETEXTURE);
ONOW_GL_DEFINE(GENSAMPLERS);
ONOW_GL_DEFINE(BINDSAMPLER);
ONOW_GL_DEFINE(DELETESAMPLERS);
ONOW_GL_DEFINE(SAMPLERPARAMETERI);
ONOW_GL_DEFINE(GENERATEMIPMAP);
ONOW_GL_DEFINE(DRAWELEMENTS);
ONOW_GL_DEFINE(DRAWELEMENTSBASEVERTEX);
ONOW_GL_DEFINE(GETSTRING);
ONOW_GL_DEFINE(GETSTRINGI);
#undef ONOW_GL_DEFINE

namespace onow {
namespace gl {

namespace {

struct Entry {
  const char* name;
  void** slot;
};

Entry* entries(size_t& count) {
  static Entry kEntries[] = {
#define ONOW_GL_ENTRY(name) {"gl" #name, reinterpret_cast<void**>(&gl##name)}
    ONOW_GL_ENTRY(VIEWPORT),
    ONOW_GL_ENTRY(SCISSOR),
    ONOW_GL_ENTRY(CLEARCOLOR),
    ONOW_GL_ENTRY(CLEAR),
    ONOW_GL_ENTRY(ENABLE),
    ONOW_GL_ENTRY(DISABLE),
    ONOW_GL_ENTRY(ISENABLED),
    ONOW_GL_ENTRY(GETINTEGERV),
    ONOW_GL_ENTRY(GETERROR),
    ONOW_GL_ENTRY(PIXELSTOREI),
    ONOW_GL_ENTRY(POLYGONMODE),
    ONOW_GL_ENTRY(BLENDEQUATION),
    ONOW_GL_ENTRY(BLENDEQUATIONSEPARATE),
    ONOW_GL_ENTRY(BLENDFUNCSEPARATE),
    ONOW_GL_ENTRY(CLIPCONTROL),
    ONOW_GL_ENTRY(CREATESHADER),
    ONOW_GL_ENTRY(SHADERSOURCE),
    ONOW_GL_ENTRY(COMPILESHADER),
    ONOW_GL_ENTRY(GETSHADERIV),
    ONOW_GL_ENTRY(GETSHADERINFOLOG),
    ONOW_GL_ENTRY(DELETESHADER),
    ONOW_GL_ENTRY(CREATEPROGRAM),
    ONOW_GL_ENTRY(ATTACHSHADER),
    ONOW_GL_ENTRY(DETACHSHADER),
    ONOW_GL_ENTRY(LINKPROGRAM),
    ONOW_GL_ENTRY(USEPROGRAM),
    ONOW_GL_ENTRY(GETPROGRAMIV),
    ONOW_GL_ENTRY(GETPROGRAMINFOLOG),
    ONOW_GL_ENTRY(DELETEPROGRAM),
    ONOW_GL_ENTRY(ISPROGRAM),
    ONOW_GL_ENTRY(GETUNIFORMLOCATION),
    ONOW_GL_ENTRY(UNIFORM1I),
    ONOW_GL_ENTRY(UNIFORM1F),
    ONOW_GL_ENTRY(UNIFORM2F),
    ONOW_GL_ENTRY(UNIFORM4F),
    ONOW_GL_ENTRY(UNIFORMMATRIX4FV),
    ONOW_GL_ENTRY(GETATTRIBLOCATION),
    ONOW_GL_ENTRY(ENABLEVERTEXATTRIBARRAY),
    ONOW_GL_ENTRY(DISABLEVERTEXATTRIBARRAY),
    ONOW_GL_ENTRY(VERTEXATTRIBPOINTER),
    ONOW_GL_ENTRY(GETVERTEXATTRIBIV),
    ONOW_GL_ENTRY(GETVERTEXATTRIBPOINTERV),
    ONOW_GL_ENTRY(GENBUFFERS),
    ONOW_GL_ENTRY(BINDBUFFER),
    ONOW_GL_ENTRY(BUFFERDATA),
    ONOW_GL_ENTRY(BUFFERSUBDATA),
    ONOW_GL_ENTRY(DELETEBUFFERS),
    ONOW_GL_ENTRY(GENVERTEXARRAYS),
    ONOW_GL_ENTRY(BINDVERTEXARRAY),
    ONOW_GL_ENTRY(DELETEVERTEXARRAYS),
    ONOW_GL_ENTRY(GENTEXTURES),
    ONOW_GL_ENTRY(BINDTEXTURE),
    ONOW_GL_ENTRY(TEXIMAGE2D),
    ONOW_GL_ENTRY(TEXPARAMETERI),
    ONOW_GL_ENTRY(DELETETEXTURES),
    ONOW_GL_ENTRY(ACTIVETEXTURE),
    ONOW_GL_ENTRY(GENSAMPLERS),
    ONOW_GL_ENTRY(BINDSAMPLER),
    ONOW_GL_ENTRY(DELETESAMPLERS),
    ONOW_GL_ENTRY(SAMPLERPARAMETERI),
    ONOW_GL_ENTRY(GENERATEMIPMAP),
    ONOW_GL_ENTRY(DRAWELEMENTS),
    ONOW_GL_ENTRY(DRAWELEMENTSBASEVERTEX),
    ONOW_GL_ENTRY(GETSTRING),
    ONOW_GL_ENTRY(GETSTRINGI),
#undef ONOW_GL_ENTRY
  };
  count = sizeof(kEntries) / sizeof(kEntries[0]);
  return kEntries;
}

std::atomic<bool> g_loaded{false};

} // namespace

void* resolve(const char* name) {
#if defined(_WIN32)
  return reinterpret_cast<void*>(::wglGetProcAddress(name));
#else
  static void* handle = nullptr;
  if (!handle) {
    handle = ::dlopen("libGL.so.1", RTLD_NOW | RTLD_GLOBAL);
    if (!handle) handle = ::dlopen("libGL.so", RTLD_NOW | RTLD_GLOBAL);
    if (!handle) handle = ::dlopen("GL", RTLD_NOW | RTLD_GLOBAL);
  }
  if (!handle) return nullptr;
  return ::dlsym(handle, name);
#endif
}

bool load(const char** missing) {
  size_t count = 0;
  Entry* table = entries(count);
  const char* first_missing = nullptr;
  for (size_t i = 0; i < count; ++i) {
    if (*table[i].slot) continue;
    void* symbol = resolve(table[i].name);
    if (!symbol && !first_missing) first_missing = table[i].name;
    *table[i].slot = symbol;
  }
  if (first_missing) {
    if (missing) *missing = first_missing;
    return false;
  }
  g_loaded.store(true);
  return true;
}

bool ready() { return g_loaded.load(); }

} // namespace gl
} // namespace onow
