#!/usr/bin/env node
/**
 * Prepares the desktop (Tauri) build inputs:
 *
 *   1. Bundles the OpenNOW backend (`src/server`) into a single ESM file at
 *      `src-tauri/resources/server.mjs` using esbuild. The bundle contains the
 *      whole dependency tree (express, ws, undici, qrcode, ...) so the desktop
 *      app needs nothing from `node_modules` at runtime.
 *   2. Stages the Node runtime as the Tauri `externalBin` sidecar:
 *      `src-tauri/binaries/opennow-server-<triple>[.exe]`. The desktop shell
 *      spawns this sidecar to run the bundled backend. On non-Windows hosts the
 *      copy is skipped unless `--force-sidecar` is passed (cross-target builds
 *      should pass an explicit `--triple <triple>` instead).
 *
 * Usage:
 *   node scripts/prepare-desktop.mjs [--triple x86_64-pc-windows-msvc] [--force-sidecar]
 */
import { build } from "esbuild";
import { copyFileSync, existsSync, mkdirSync, statSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const resourcesDir = join(root, "src-tauri", "resources");
const binariesDir = join(root, "src-tauri", "binaries");

const args = process.argv.slice(2);
const tripleFlagIndex = args.indexOf("--triple");
const triple =
  tripleFlagIndex !== -1 && args[tripleFlagIndex + 1]
    ? args[tripleFlagIndex + 1]
    : defaultTriple();

function defaultTriple() {
  const arch = process.arch === "x64" ? "x86_64" : process.arch === "arm64" ? "aarch64" : null;
  if (!arch) throw new Error(`Unsupported architecture: ${process.arch}`);
  switch (process.platform) {
    case "win32":
      return `${arch}-pc-windows-msvc`;
    case "linux":
      return `${arch}-unknown-linux-gnu`;
    case "darwin":
      return `${arch}-apple-darwin`;
    default:
      throw new Error(`Unsupported platform: ${process.platform}`);
  }
}

mkdirSync(resourcesDir, { recursive: true });
mkdirSync(binariesDir, { recursive: true });

// ---------------------------------------------------------------------------
// 1. Backend bundle
// ---------------------------------------------------------------------------
const outfile = join(resourcesDir, "server.mjs");
await build({
  entryPoints: [join(root, "src", "server", "index.ts")],
  outfile,
  bundle: true,
  // ESM keeps the server's top-level await working; the sidecar runs it with
  // plain `node server.mjs`.
  format: "esm",
  platform: "node",
  target: "node22",
  // `vite` is only imported in the development branch of the server and is
  // never evaluated in production (NODE_ENV=production), so it stays external
  // instead of adding ~10 MB of dev-server code to the bundle.
  external: ["vite"],
  // Keep the bundle unminified so support requests can be debugged from
  // server.log stack traces without a source map.
  minify: false,
  sourcemap: false,
  logLevel: "info",
  banner: {
    js: [
      "// OpenNOW desktop backend bundle — generated by scripts/prepare-desktop.mjs.",
      "// Do not edit; run `npm run desktop:prepare` to regenerate.",
      "import { createRequire as __opennowCreateRequire } from \"node:module\";",
      "// Bundled CommonJS dependencies (e.g. the `debug` package pulled in by",
      "// express) call require() for Node builtins at runtime. ESM output has no",
      "// require of its own, so provide one rooted at this file.",
      "const require = __opennowCreateRequire(import.meta.url);",
    ].join("\n"),
  },
});
console.log(`[desktop] bundled backend -> ${relative(root, outfile)}`);

// ---------------------------------------------------------------------------
// 2. Node sidecar executable
// ---------------------------------------------------------------------------
const sidecarName = `opennow-server-${triple}${process.platform === "win32" ? ".exe" : ""}`;
const sidecarTarget = join(binariesDir, sidecarName);
const shouldStageSidecar = process.platform === "win32" || args.includes("--force-sidecar");

if (shouldStageSidecar) {
  // process.execPath is the exact Node runtime that was validated by this
  // repo's tooling (Node >= 22). Copying it avoids surprises from whatever
  // Node (if any) is installed on the end-user's machine.
  const source = process.execPath;
  const sourceSize = statSync(source).size;
  if (existsSync(sidecarTarget) && statSync(sidecarTarget).size === sourceSize) {
    console.log(`[desktop] sidecar already staged    -> ${relative(root, sidecarTarget)}`);
  } else {
    copyFileSync(source, sidecarTarget);
    console.log(`[desktop] staged Node sidecar      -> ${relative(root, sidecarTarget)}`);
  }
} else {
  console.log(
    `[desktop] skipped Node sidecar stage (${sidecarName}); run on Windows or pass --force-sidecar`,
  );
}

// ---------------------------------------------------------------------------
// 3. NVST native-streamer sidecar (best-effort local build)
// ---------------------------------------------------------------------------
// CI builds the canonical sidecar from the vendored engine in the
// `nvst-sidecar` job and stages it into src-tauri/binaries before bundling.
// Locally, attempt the same build so `tauri build` keeps working without CI;
// a missing Rust toolchain only disables native playback, it never breaks
// the WebRTC app, so any failure here warns and continues.
const nvstName = `opennow-nvst-${triple}${process.platform === "win32" ? ".exe" : ""}`;
const nvstTarget = join(binariesDir, nvstName);
const nvstCrateDir = join(root, "third_party", "opennow-streamer");

if (existsSync(nvstTarget)) {
  console.log(`[desktop] NVST sidecar already staged -> ${relative(root, nvstTarget)}`);
} else if (!existsSync(join(nvstCrateDir, "Cargo.toml"))) {
  console.log("[desktop] NVST sidecar skipped (vendored engine not present)");
} else {
  try {
    console.log("[desktop] building NVST sidecar from vendored engine (best-effort)...");
    execFileSync("cargo", ["build", "--release", "-p", "opennow-streamer"], {
      cwd: nvstCrateDir,
      stdio: "inherit",
    });
    // The crate's binary target keeps its package name; rename into the
    // externalBin lookup slot (`opennow-nvst-<triple>[.exe]`) on stage.
    const builtExe = join(
      nvstCrateDir,
      "target",
      "release",
      `opennow-streamer${process.platform === "win32" ? ".exe" : ""}`,
    );
    copyFileSync(builtExe, nvstTarget);
    console.log(`[desktop] staged NVST sidecar     -> ${relative(root, nvstTarget)}`);
  } catch (error) {
    console.warn(
      `[desktop] NVST sidecar build failed (${error instanceof Error ? error.message : String(error)}); continuing without native playback`,
    );
  }
}
