import type { Settings } from "@shared/gfn";
import {
  DEFAULT_KEYBOARD_LAYOUT,
  DEFAULT_VIDEO_SHADER_SETTINGS,
  getDefaultStreamPreferences,
} from "@shared/gfn";

const streamPreferences = getDefaultStreamPreferences();

export const WEB_DEFAULT_SETTINGS: Settings = {
  resolution: "1920x1080",
  aspectRatio: "16:9",
  posterSizeScale: 1.05,
  fps: 60,
  maxBitrateMbps: 75,
  recordingBitrateMbps: null,
  streamClientMode: "native",
  nativeStreamerBackend: "gstreamer",
  nativeVideoBackend: "auto",
  nativeStreamerExecutablePath: "",
  nativeCloudGsyncMode: "auto",
  nativeD3dFullscreenMode: "auto",
  nativeExternalRenderer: false,
  transportMode: "webrtc",
  showNativeStreamerStats: false,
  codec: streamPreferences.codec,
  decoderPreference: "auto",
  encoderPreference: "auto",
  colorQuality: streamPreferences.colorQuality,
  region: "",
  sessionProxyEnabled: false,
  sessionProxyUrl: "",
  clipboardPaste: false,
  enableGyroscopeControls: false,
  steamControllerCompatibilityMode: false,
  nativeCursorOverlay: true,
  mouseSensitivity: 1,
  mouseAcceleration: 1,
  shortcutToggleStats: "F3",
  shortcutTogglePointerLock: "F8",
  shortcutToggleFullscreen: "F10",
  shortcutStopStream: "Ctrl+Shift+Q",
  shortcutToggleAntiAfk: "Ctrl+Shift+K",
  shortcutToggleMicrophone: "Ctrl+Shift+M",
  shortcutScreenshot: "F11",
  shortcutToggleRecording: "F12",
  microphoneMode: "disabled",
  microphoneDeviceId: "",
  hideStreamButtons: false,
  showAntiAfkIndicator: true,
  showStatsOnLaunch: true,
  hideServerSelector: false,
  appAccentColor: "green",
  appTheme: "auto",
  translucentUI: false,
  controllerMode: false,
  launchInConsoleMode: false,
  autoFullScreen: false,
  favoriteGameIds: [],
  sessionCounterEnabled: false,
  showSessionTimeRemainingInStatsOverlay: false,
  sessionClockShowEveryMinutes: 60,
  sessionClockShowDurationSeconds: 30,
  windowWidth: 1400,
  windowHeight: 900,
  keyboardLayout: DEFAULT_KEYBOARD_LAYOUT,
  gameLanguage: "en_US",
  enablePersistingInGameSettings: true,
  enableL4S: false,
  enableCloudGsync: false,
  nativeTransitionDiagnostics: undefined,
  discordRichPresence: false,
  autoCheckForUpdates: false,
  updateChannel: "stable",
  allowEscapeToExitFullscreen: false,
  lastSeenReleaseHighlightsVersion: "0.5.1-web",
  videoShader: { ...DEFAULT_VIDEO_SHADER_SETTINGS },
};
